### ISSUE TITLE
Svelte 3.30.0 breaks the Router Component

### ISSUE THREAD

**Issue by ShadowfeindX** [ItalyPaleAle/svelte-spa-router#168] opened 2020-12-01 06:13 UTC
In the Svelte 3.30.0 update the `SvelteComponent` and `SvelteComponentDev` interfaces were changed to be strongly typed. This means that the type of imported Components is now incompatible with these interfaces leading to errors like this:
```
Type '{ "/": typeof Index; }' is not assignable to type 'RouteDefinition'.
  Type '{ "/": typeof Index; }' is not assignable to type 'Record<string, typeof SvelteComponentDev | WrappedComponent>'.
    Property '"/"' is incompatible with index signature.
      Type 'typeof Index__SvelteComponent_' is not assignable to type 'typeof SvelteComponentDev | WrappedComponent'.
        Types of construct signatures are incompatible.
          Type 'new (options: Svelte2TsxComponentConstructorParameters<Partial<{}>>) => Index__SvelteComponent_' is not assignable to type 'new <Props extends Record<string, any> = any, Events extends Record<string, any> = any, Slots extends Record<string, any> = any>(options: { target: Element; anchor?: Element; props?: Props; hydrate?: boolean; intro?: boolean; $$inline?: boolean; }) => SvelteComponentDev<...>'.
            Construct signature return types 'Index__SvelteComponent_' and 'SvelteComponentDev<Props, Events, Slots>' are incompatible.
              The types of '$on' are incompatible between these types.
                Type '<K extends string | number>(event: K, handler: (e: { [evt: string]: CustomEvent<any>; }[K]) => any) => () => void' is not assignable to type '<K extends Extract<keyof Events, string>>(type: K, callback: (e: Events[K]) => void) => () => void'.
                  Types of parameters 'handler' and 'callback' are incompatible.
                    Types of parameters 'e' and 'e' are incompatible.
                      Type 'CustomEvent<any>' is not assignable to type 'Events[K]'.
```
A temporary solution is to just stick to Svelte 3.29.7, but I'm sure this will eventually need to be addressed.

I'm not exactly sure how to go about fixing something like this since I'm relatively new to Svelte. If this is something that needs to be brought to the attention of the Svelte team rather than here please let me know so I can make the appropriate issue there.

**Comment by ItalyPaleAle** [comment] 2020-12-01 16:31
Thanks for reporting this, I'll take a look tonight

**Comment by dummdidumm** [comment] 2020-12-01 18:13
Language-tools-maintainer here, sorry for the inconvenience. I will look into how breakage like this can possibly avoided by relaxing the `SvelteComponent` types a little or by changing something inside the language-tools definitions.

Note that the update to use the typed `SvelteComponent` is technically a breaking change because people need to use version 3.30+ of Svelte for this to work.

**Comment by ItalyPaleAle** [comment] 2020-12-01 18:33
@dummdidumm thanks for chiming in!

I played around with this a bit in the morning, before starting work.

The issue is that, before the PR that implemented generic typings, I was already offering typings using the "old" format: https://github.com/ItalyPaleAle/svelte-spa-router/blob/v3.0.5/Router.d.ts#L162

When the new typings got merged, sadly the old ones stopped working.

I haven't finished working on the new typings and plan to look at this again tonight, but I did realize this was a breaking change and was already thinking how to communicate this.

1. The biggest issue is for people using TypeScript. I was thinking I could make svelte ^3.30.0 as peerDependency to signal to people that they should be using at least that version. I can also add to the docs that using TypeScript will require Svelte 3.30 or higher.
2. People who aren't using TypeScript shouldn't be impacted, however if they are using Svelte < 3.30.0 they will see errors in the editor (but that won't impact compile-time).

If there's a way you can relax the types, however, that would be amazing!

**Comment by ItalyPaleAle** [comment] 2020-12-02 04:36
@dummdidumm I have made a code change to match the strong types, but it doesn't look like it's correct anyways: https://github.com/ItalyPaleAle/svelte-spa-router/commit/ba2658ec80863285dfae7044299f05ca757e64bc

It seems the types are still too strict and it won't work for a router like this. I've been thinking about this but I'm low on ideas at this point and wondering if this is something that needs to be fixed upstream :(

**Comment by dummdidumm** [comment] 2020-12-02 06:39
It needs to be fixed upstream. The problem is that typescript will always complain when `typeof SomeClassWithGenerics = Subclass` it seems. We need to revert the typed `SvelteComponent` and instead provide that functionality through a separate class.

**Comment by ItalyPaleAle** [comment] 2020-12-02 06:47
Thanks for confirming. I've reverted my last attempt for now and we'll wait for a change upstream

**Comment by dummdidumm** [comment] 2020-12-02 21:38
This should be fixed with Svelte version 3.31.0. Nothing to do on your part @ItalyPaleAle .

**Comment by ItalyPaleAle** [comment] 2020-12-02 21:47
Thank you @dummdidumm for submitting a fix upstream!

@ShadowfeindX can you please confirm this is working for you too now?

**Closed** 2020-12-02 21:47 UTC

**Comment by ShadowfeindX** [comment] 2020-12-03 04:27
@ItalyPaleAle yes this works perfectly for me! Thanks for the quick response @dummdidumm!
