### ISSUE TITLE
Feature request: onBefore

### ISSUE THREAD

**Issue by rottmann** [ItalyPaleAle/svelte-spa-router#43] opened 2019-10-24 10:03 UTC
When click a link and before route to the target, it would be nice to have a global onBefore function or a onBefore on each route (or both).

E.g. if a page has modified fields, you can ask in a modal to save before leaving the page.

Currently you must implement it on your own on each link
```
<script>
function beforeSwitch() {
  if (isModified && alert('Leave?')) {
    const url = new URL(this.href)
    push(url.hash.substr(1)) // remove # and route to target
  }
}
</script>

<a href="#/target" on:click|preventDefault={beforeSwitch}>Link</a>
```

**Comment by ItalyPaleAle** [comment] 2019-10-24 20:26
This is great timing :) I created #40 as a draft last night and would be great if you could provide feedback on that design.

(Closing as duplicate of #23 and #40)

**Closed by ItalyPaleAle** 2019-10-24 20:26 UTC
