### ISSUE TITLE
Name parameter does not changes when changed in browser address bar

### ISSUE THREAD

**Issue by azakost** [ItalyPaleAle/svelte-spa-router#160] opened 2020-10-30 06:06 UTC
1. Setted route with named parameter in routes.js:

```
import Post from "./pages/post.svelte";
export const routes = new Map();
routes.set("/posts/:id", Post);
```
2. In Post component
```
<script>
export let params;
console.log(params.id);
</script>
{ params.id } 
```

For example if I click on link "/posts/123" right in webapp - it works well,
but if I change this link to "/posts/5" in browser's address bar - 'params.id' still lasts as "123"

**Comment by ItalyPaleAle** [comment] 2020-10-30 06:10
I just tested this and it's working for me - cannot reproduce it!

What is your environment?

**Comment by azakost** [comment] 2020-10-30 06:22
Sorry, forgot to add in my example 'console.log(params.id)'. Edited issue.
Please run (by changing in addressbar and hitting 'enter' key) and see difference.

**Comment by azakost** [comment] 2020-10-30 06:27
It seems like page has to be refreshed after any change of named parameters. Otherwise it still works like an anchor.

**Comment by ItalyPaleAle** [comment] 2020-10-30 06:32
Well, `console.log` will only be triggered once because it's not a reactive statement. To get that triggered every time `params.id` change you need to replace the line with:

```svelte
$: console.log(params.id)
```

See: https://svelte.dev/tutorial/reactive-declarations

In the template, `{params.id}` should be reactive by default.

**Comment by azakost** [comment] 2020-10-30 07:29
Well, I think it should fully act like any other non-hash based router. That's a core thing i am talking about.

**Comment by ItalyPaleAle** [comment] 2020-10-30 07:31
I'm not sure what you mean with that. The router follows the principles of reactivity of Svelte 3.

Can you give me an example of another router and its behavior?

**Comment by ItalyPaleAle** [comment] 2020-10-30 07:49
I am not familiar with many other routers to this level so I can't comment on their behavior fully. However, I don't think this is about hash-based routing.

In Svelte 3, code inside the script block is executed only once, when the component is mounted the first time. To make code execute reactively, you can use the `$:` label.

Now, when you change page from /posts/123 to /posts/456, the component is the same. So, the router does not un-mount and re-mount the component. This means that the code in the script block is not re-executed, unless you make the statements reactive by binding them to props.

The fact that the component is not un-mounted is a design decision: it minimizes the amount of re-renderings and so it gives best performance. It's also consistent with the patterns of Svelte 3 (which recommend re-rendering only what's updated and encourages using reactive statements). You can find a discussion on the topic in #148

Closing this for now as it seems to be working as intended. But feel free to comment further.

**Closed** 2020-10-30 07:49 UTC
Labels: duplicate, wontfix

**Comment by azakost** [comment] 2020-10-30 07:59
Still feel that routes with named parameter should act like other routes without it.

This is rithorical issue. Anyway thanks for your job!
