### ISSUE TITLE
Nested route child components don't re-render

### ISSUE THREAD

**Issue by mphuie** [ItalyPaleAle/svelte-spa-router#97] opened 2020-04-01 18:23 UTC
I have a simple master-detail 2 pane view, using nested routes.

I've noticed that when I click on a child link, the component only renders once.  Subsequent clicks on other links change the URL, but the component isn't rerendered.

I saw another thread on this, but can't figure out how to destroy/re-create the child component.  Is there a good way to do this?  `params` updates but the my child component is making a HTTP request during onMount, which does not re-run.

**Comment by frederikhors** [comment] 2020-04-01 18:35
REPL please.

**Comment by ItalyPaleAle** [comment] 2020-04-01 18:37
So, if the component doesn't change, Svelte doesn't re-create it, and this is by design.

However, there could be a relatively simple solution here to your problem: rather than fetching the data in an `onMount` callback, you could listen to the `params` object and invoke your method reactively.

For example, from:

```js
onMount(() => {
    loadData()
})
```

To:

```js
import {location} from 'svelte-spa-router'
$: location && loadData()
```

(Untested, but hopefully it gives you the idea!)

**Comment by mphuie** [comment] 2020-04-01 18:41
Thanks for the quick reply, will try that.  For now I was putting my component in an `#if` block and setting it to false, then true in a `setTimeout` to get it to re-render. 

`function setSelected(id) {
    selectedId = null;
    setTimeout(() => selectedId = id, 0);
}`

**Comment by ItalyPaleAle** [comment] 2020-04-01 18:48
That might work too.

I'm closing this issue but feel free to comment more if it doesn't work.

**Closed by ItalyPaleAle** 2020-04-01 18:48 UTC
Labels: question
