### ISSUE TITLE
Does not re-route on hashchange event

### ISSUE THREAD

**Issue by brandonbloom** [ItalyPaleAle/svelte-spa-router#233] opened 2021-07-28 17:02 UTC
If you manually edit the hash in your browser's address bar, a `hashchange` event fires, but svelte-spa-router does not automatically rerender the routes with the new location.

**Comment by ItalyPaleAle** [comment] 2021-07-28 17:08
It should do what you describe and it's one thing that it's also tested in the CI.

Can you share more context please? Both the environment (browser, etc), and possibly some code. If you could create a small repro, that would be great.

**Comment by brandonbloom** [comment] 2021-07-28 21:25
Hm, @BenElgar reported this to me and I was also seeing it locally, but now I'm not. @BenElgar are you still able to reproduce? If not, apologies for the noise @ItalyPaleAle!

**Comment by ItalyPaleAle** [comment] 2021-07-31 11:17
Closing this as I cannot reproduce it either. If you still have issues please leave a comment with some more details and I'll reopen this!

**Closed by ItalyPaleAle** 2021-07-31 11:17 UTC
