### ISSUE TITLE
On slower devices the browser does not correctly reset the scroll when I go back to the list

### ISSUE THREAD

**Issue by frederikhors** [ItalyPaleAle/svelte-spa-router#146] opened 2020-10-08 15:31 UTC
**Packages versions**

```json
"svelte": "3.29.0",
"svelte-spa-router": "3.0.3"
```

# First reproduction

**Steps to reproduce**

1. Start the server opening this page: https://codesandbox.io/s/apollo-server-urql-svelte-crud-h1pcl
1. Open Incognito browser session
1. Go to reproduction: https://bjr5y.csb.app/
1. Click on "Todos list"
1. Click on "Add more random todos" button many times so the scrollbar becomes visible and **Q.ty is >= 100**
1. Scroll down and click on the last todo link "Open"
1. The todo shows
1. Go back with browser button
1. The list page is scrolled down, as it should be
1. Open the browser Dev Tools
1. Go to "Performance" tab
1. Change "CPU:" to "6x slowdown"
1. Click again on the last todo link "Open"
1. The todo shows
1. Go back with browser button
1. The list page is no longer scrolled down

**Expected behavior**

Also on slower devices the browser correctly reset the scroll when I go back to the list.

**Actual behavior**

On slower devices the browser does not correctly reset the scroll when I go back to the list. The scroll is always at the top of the page.

**Additional**

I think when I go back the DOM is still not there, the browser doesn't wait all the rendering to succeed before scrolling down the page.

If the CPU is fast this happens. If CPU is slow NOT.

What to do?

Is there a way to tell the browser to wait for the list to render before resetting the scroll?

**Gif reproduction**

![issue](https://user-images.githubusercontent.com/41120635/95481502-5cfc2800-098d-11eb-9189-761a2d96a48f.gif)

# Second reproduction

In this case the steps are the same but you should click on "Todos list rAF".

![image](https://user-images.githubusercontent.com/41120635/95507004-0bfe2b00-09b1-11eb-82e5-ff649aea31f2.png)

Here I am using a technique taken from here: https://github.com/ItalyPaleAle/svelte-spa-router/issues/77#issuecomment-593607896.

@jacwright what do you think about this issue? Your solution with `RequestAnimationFrame` is **really** awesome but is there a way to handle browser back button scroll position?

---

[CodeSandBox client project](https://codesandbox.io/s/svelte-spa-router-restorescrollstate-doesnt-work-bjr5y)
[CodeSandBox server project](https://codesandbox.io/s/apollo-server-urql-svelte-crud-h1pcl)

**Comment by frederikhors** [comment] 2020-10-08 15:40
Update: added Gif reproduction.

**Comment by BogdanDarius** [comment] 2020-10-08 16:06
@frederikhors
I cant reproduce this on Chromium Version 86.0.4240.75.

**Comment by frederikhors** [comment] 2020-10-08 17:26
Oh! Wow!

Maybe your device is powerful.

Can you try to increase the todos in the list up to 1000?

**Comment by BogdanDarius** [comment] 2020-10-08 17:29
> Oh! Wow!
> 
> Maybe your device is powerful.
> 
> Can you try to increase the todos in the list up to 1000?

I tried with 2000 items. The scrollbar is still at the bottom.
Very strange indeed.

**Comment by frederikhors** [comment] 2020-10-08 17:43
Is CPU 6x slowdown?

**Comment by BogdanDarius** [comment] 2020-10-08 17:44
> Is CPU 6x slowdown?

Yes

**Comment by frederikhors** [comment] 2020-10-08 20:00
I updated with a second reproduction case.

@BogdanDarius I think you will see the problem using this second case.

**Comment by vigenere23** [comment] 2020-10-26 17:04
For me it never worked... I had to implement it myself. Also using `3.x.x` for both svelte and spa-router, tested on Chromium and Firefox (latest) and Safari iOS and Firefox mobile.

**Comment by ItalyPaleAle** [comment] 2020-10-29 04:12
Sorry for responding late, as I was thinking about this issue. This has the look and smell of a race condition.

One thing I noticed in your repro code while playing with it, is that you didn't set `restoreScrollState={true}`. Is there a reason for that?

Oddly, however, when setting that value, now I can't get the scroll position restored even with normal CPU performance. Will do some debugging.

**Comment by ItalyPaleAle** [comment] 2020-10-29 04:16
I made a fork in which I enabled `restoreScrollState` and changed your links in the List component to use `use:link`, and it seems to be working even with 6x slowdown: https://codesandbox.io/s/svelte-spa-router-restorescrollstate-forked-rxm5t

Demo: https://rxm5t.csb.app/#/todos

**Comment by frederikhors** [comment] 2020-10-29 09:27
Is there a way to avoid `use:link`?

**Comment by ItalyPaleAle** [comment] 2020-10-29 15:29
No, sadly, it's a requirement. This was recently asked in #155 too: the scroll position must be saved before the navigation happens, so use:link (or using push) is necessary.

**Comment by ItalyPaleAle** [comment] 2020-10-29 23:11
@frederikhors please let me know if using `restoreScrollState` fixes it for you and so if I can close this issue!

**Comment by frederikhors** [comment] 2020-10-29 23:19
Can you give me a day, please?

**Comment by ItalyPaleAle** [comment] 2020-10-29 23:21
Absolutely!!!

**Comment by frederikhors** [comment] 2020-10-30 18:14
Have you read this last message of mine, @ItalyPaleAle?

**Comment by ItalyPaleAle** [comment] 2020-10-30 18:32
Yes sorry I'm going to look into it tonight.

What are the repro steps? The same ones in your first post above? Does it reproduce consistently or only some times? In what browser are you testing, and are you testing within codesandbox or `csb.app` site?

**Comment by frederikhors** [comment] 2020-10-30 19:12
> Yes sorry I'm going to look into it tonight.

Please don't be sorry at all!

> What are the repro steps? The same ones in your first post above?

Yes, the same. Just use this: https://codesandbox.io/s/svelte-spa-router-restorescrollstate-forked-tcfvj?file=/App.svelte.

It's the same of the first one, plus `use:link` and `restoreScrollState={true}`.

Note the problem is also on `todos_raf` directory / example.

> Does it reproduce consistently or only some times?

Every time.

> In what browser are you testing?

Chrome 86, Windows 10.

> are you testing within codesandbox or csb.app site?

Both. Also w/ Incognito mode.

**Comment by ItalyPaleAle** [comment] 2020-11-05 05:22
@frederikhors I took a look and looks like you're using nested routers, so you need to set `restoreScrollState={true}` in the nested router. Can you try and see if that works?

**Comment by frederikhors** [comment] 2020-11-06 14:58
I tried. You're right. I forgot `restoreScrollState` on nested router.

However the "problem" remains in the "Todos Raf" section as you can see.

In part I think this is right because the DOM does not exist when I go back to the list, but this is the real challenge: can we use the restore even in this situation?

I am using the Raf (requestAnimationFrame) a lot because it makes browsing much faster in the eyes of users.

**Comment by ItalyPaleAle** [comment] 2020-11-16 00:03
Yes this would make sense. The scroll position is restored after the component is mounted, but because your component has some async stuff in the `onMount` section, there might be a timing issue..

Your best bet at this point is to perform the scroll manually when your app is ready for that. You'll have to save the scroll position before navigating, and restoring it when ready.

You can see an example here: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Router.svelte#L406-L429

I'm closing this issue because it's not a bug with the router itself.

**Closed by ItalyPaleAle** 2020-11-16 00:03 UTC

**Comment by frederikhors** [comment] 2020-11-16 01:14
Thanks @ItalyPaleAle.

It would be great if this kind of thing natively belonged to the router I'm using.

But I realize it's an advanced feature (I'm referring to the `requestAnimationFrame` and its relative scroll).

Thanks for everything.
