### ISSUE TITLE
snowpack 3 issue: Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by edeleastar** [ItalyPaleAle/svelte-spa-router#193] opened 2021-02-05 09:49 UTC
Under certain circumstances - not always reproducible - snowpack 3 is generating the following error on start:

~~~
Uncaught TypeError: Failed to resolve module specifier "svelte-spa-router". Relative references must start with either "/", "./", or "../".
~~~

This was in a project based on this template:

- <https://github.com/LBrian/app-template-s2t2>

The project in question is here:

- <https://github.com/edeleastar/tutors-snowpack>

**Comment by ItalyPaleAle** [comment] 2021-03-02 02:48
Especially if this is not always reproducible, this sounds like a bug in Swnopack and their module resolution. Can you try filing a bug upstream?

I'm closing this for now, but if it turns out it's something we're doing, can reopen.

**Closed by ItalyPaleAle** 2021-03-02 02:48 UTC
