### ISSUE TITLE
Cannot find module 'svelte-spa-router' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by Parables** [ItalyPaleAle/svelte-spa-router#140] opened 2020-09-30 19:16 UTC
Recently upgraded Svelte and I am seeing this everywhere I use push, pop or location. Can you please fix that for me asap?

**Comment by ItalyPaleAle** [comment] 2020-09-30 19:38
I'm working on this project as a volunteer so I can't "fix that for [you] asap".

In any case, the report lacks information. What is the error that you're getting, and most importantly where are you seeing it? And what are you doing when the error appears? Please provide a clear report.

What you wrote is mentioning the TypeScript typings so I wonder if it's an error in your tooling, such as your IDE? In which case, make sure that your Node modules are installed correctly, and try re-starting your IDE?

**Comment by dljsjr** [comment] 2020-09-30 22:24
I don't wish to necro but I am seeing the same issue: even though Router.svelte has type annotations the base module itself doesn't seem to.

Of note, the following gives the aforementioned linting error:

```typescript
import Router from "svelte-spa-router";
```

**HOWEVER**, if you import Router.svelte directly then there is no issue, the typings get picked up just fine:

```typescript
import Router from "svelte-spa-router/Router.svelte";
```

**Comment by ItalyPaleAle** [comment] 2020-09-30 22:25
Where do you see this error?

**Comment by ItalyPaleAle** [comment] 2020-09-30 22:26
And are you able to share some code to reproduce this?

**Comment by dljsjr** [comment] 2020-09-30 22:38
It appears to be the output of `svelte-check`. It shows up as a "red squiggly" in VS Code and I can reproduce it locally with `$(yarn bin)/svelte-check` in my local project.

I don't have a public repo I can share currently, but it can be reproduced with a very simple Svelte app and the following App.svelte:

```
<script lang="ts">
  import Home from "./routes/Home.svelte";
  import NotHome from "./routes/NotHome.svelte";
  import Router, { link } from "svelte-spa-router";

  const routes = {
    "/": Home,
    "/not_home": NotHome,
  };
</script>

<ul>
  <li><a href="/" use:link>Home</a></li>
  <li><a href="/not_home" use:link>Not Home</a></li>
</ul>
<Router {routes} />

```

**Comment by ItalyPaleAle** [comment] 2020-10-01 00:49
I see, you're using TypeScript. Let me take a look and see what I can come up with.

**Comment by BogdanDarius** [comment] 2020-10-01 01:05
Hello there!
In order to fix typescript erros just add `svelte-spa-router` to decs.d.ts file.
```ts
declare module "svelte-spa-router";
// add active or wrap if needed
declare module "svelte-spa-router/active";
declare module "svelte-spa-router/wrap";
```

**Comment by ItalyPaleAle** [comment] 2020-10-01 02:09
So, I've looked into this and I can repro when using TypeScript.

However, I don't think this is an issue with this package. The point of TS is that it should work transparently with non-TS modules, and this module isn't written in TS (although we do have JSDoc comments, so typings should work).

What I think the issue is: unlike "traditional" NPM modules, this router exports a Svelte file and not a pre-compiled JS document. This is by design, as packages for Svelte components should export the `.svelte` file directly: this makes sure that the file is compiled with the same Svelte compiler as the rest of the app, and possibly enables more optimizations in the compiler.

It seems that the TypeScript support in Svelte is having issues with packages that don't export a JS or TS file. Ideally, it should recognize that the package is exporting a `.svelte` file, and tooling should be able to pick typings up from the embedded JSDoc.

My recommendation is to open an issue with the maintainers of TS support for Svelte here: https://github.com/sveltejs/language-tools
It might actually be related to this issue, given how `push`, `pop`, etc are exported from a `<script type="module">` block: https://github.com/sveltejs/language-tools/issues/550

**Comment by ItalyPaleAle** [comment] 2020-10-01 02:10
Said that, thanks a lot @BogdanDarius for the workaround for now 😄 Although, that reinforces even more the theory that this is an issue in the Svelte tooling and should be fixed upstream.

**Closed by ItalyPaleAle** 2020-10-01 02:10 UTC
Labels: on-hold

**Comment by dljsjr** [comment] 2020-10-01 14:04
Ah yes, sorry I thought it was known this was a TypeScript specific problem!

I'm aware of @BogdanDarius's workaround for modules that don't expose types but since the Svelte component was annotated with JSDoc I figured there was some other issue.

The other workaround of course being to import Router.svelte directly instead of just the module.

**Comment by gdamjan** [comment] 2020-10-08 20:22
> Hello there!
> In order to fix typescript errors just add `svelte-spa-router` module to **decs.d.ts** file.

where do we add this?

**Comment by dljsjr** [comment] 2020-10-08 20:58
I might be wrong (I'm not a TS expert) but I believe @BogdanDarius is suggesting having a project local typescript modules declarations file to just silence the linter but it won't actually bring the typings in to scope. You have to import the .svelte component to do that like in my original workaround.

**Comment by BogdanDarius** [comment] 2020-10-08 21:01
@gdamjan in **src** of your project where you would usually have **App.svelte** make a **decs.d.ts** and declare any unknown types there if you want to get around the warnings.

**Comment by gdamjan** [comment] 2020-10-08 21:38
Thanks both! I'll import the `'svelte-spa-router/Router.svelte'` directly until this is fixed in svelte tooling.

**Comment by ItalyPaleAle** [comment] 2020-10-22 01:51
Thanks to #152, we should now have TypeScript definitions and types! I'm about to release v 3.0.4 soon

**Comment by buzzy** [comment] 2025-04-19 23:04
I am still getting type error in vscode. Do I still have to add types manually?

![Image](https://github.com/user-attachments/assets/a15ed9fd-6618-4720-bdb5-74f1a88bfbc1)
