### ISSUE TITLE
Page doesn't re-render when URL parameter changes

### ISSUE THREAD

**Issue by rondonjon** [ItalyPaleAle/svelte-spa-router#116] opened 2020-05-22 14:46 UTC
How to reproduce:

 - configure a route with a parameter, e.g. `item/:itemId`
 - navigate to a valid route, e.g. `item/7`
 - change the `itemId` parameter value, e.g. `item/8`, in the browser address bar and hit enter

Expected result:

 - browser should fire a `hashchange` event
 - router should replace the page content for item 7 with the content of item 8

Actual result:

 - browser fires a `hashchange` event :heavy_check_mark: 
 - router doesn't replace the page content (still showing item 7) :x:

**Comment by ItalyPaleAle** [comment] 2020-05-25 03:02
I cannot reproduce this. I've done this multiple times, and it's always worked for me.

Could you please share some code to reproduce it and provide information on what is the environment you're testing against?

**Comment by crazedVic** [comment] 2020-05-29 22:01
I ran into a similar issue recently.  I have a navigation bar:
```
<li>
<a use:link use:active href="/Parents/all"><i class="fa fa-user-friends fa-lg"></i> Parents </a>
</li>
 <li>
<a use:link use:active href="/Parents/noservice"> <i class="fa fa-sad-tear fa-lg"></i> Waitlist </a>
</li>
```

And i tried to do this:
```
const routes = {
        '/Parents/all': Parents,
        '/Parents/noservice': Parents,
    }
```

And then in the Parents.svelte onMount:
```
let status = "_" + $location.substring($location.indexOf("/Parents/") + 9);
fetch(url + 'sitter/profiles/status/parents' + status, options)
```

When you click on either navigation link, the url changes but since it's the same svelte component, namely Parents.svelte, it's not triggering a reload.

Clicking on a link to another component and then coming back to either of the above ones works, but you cannot flip between the two.  It will change the url in the location bar but the component does not reload.

I tried a few workarounds, in the end i created a simple wrapper component for each status, here is All.svelte:
```
<script>
    import Parents from "../../Parents.svelte";
</script>
<Parents/>
```
and i changed my routes configuration point to the wrapper components to:
```
import Parents_all from './profile/status/parent/All.svelte';
    import Parents_noserv from './profile/status/parent/Noservice.svelte';
const routes = {
        '/Parents/all': Parents_all,
        '/Parents/noservice': Parents_noserv,
}
```

it is super ugly but it works.  I tried also using events but this was even less pretty:
```
<a href="/Applications/all"
                       use:link use:active on:click={() => onClick('all')}> All </a>
```
which runs:
```
function onClick(target){
        //console.log(target);
        dispatch('navigate', {target: target})
    }
```
which in turn is handled here:
```
function handleNavigation(event){
        replace('/Applications?status=' + event.detail.target);
    }
```
and then i was able to show all status from one component, and it did refresh when i clicked on different status.

hope that helps.

**Comment by ItalyPaleAle** [comment] 2020-05-30 01:19
I think I understand the issue now and I actually think this is the correct behavior of the router.

The router should not un-mount and re-mount routes if the route doesn't change. That would almost always require a re-rendering of a lot of content and would have bad performance.

Because the component is only mounted once, `onMount` is only executed once, and that's by design. _(By the way, if you use this router, you might not need to execute code with `onMount`: unless you're using server-side rendering - which this router was designed to avoid - using `onMount` is redundant and you could just put your initialization code in the script block)_

Instead, you can achieve your goals using Svelte's reactivity on the params prop.

For example, let's say that your page loads the content using a promise in a variable `promise`, you could do something like:

```svelte
{#await promise}
...
{:then result}
...
{/await}
<script>
export let params = {}
$: promise = fetch(url + 'sitter/profiles/status/parents' + params.parentId, options)
</script>
```

Because we're using a reactive statement to define the promise (`$: promise`), Svelte will re-execute that line every time the `params.parentId` prop (assuming the prop from the URL is `parentId`) changes.

This will ensure that Svelte re-renders only the stuff that has changed.

**Comment by crazedVic** [comment] 2020-05-30 18:16
So if I understand you correctly, the URL change is purely cosmetic as it's not something that svelte can react to.   Instead we would keep the status or id in a writable store, and clicking a link would then cosmetically alter the url as it does now without any reaction, but it would also need to change the value in the writable store which is reactive and would trigger a new fetch?

**Comment by ItalyPaleAle** [comment] 2020-05-30 18:23
Svelte can only react to changes in the DOM. URLs shown in the browsers' bar are not in the DOM, so Svelte can't react to that. The router however has a listener to URL changes events and sets the value of the `$loc` store to always match what's in the URL: https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/Router.svelte#L78 If you use the router, you don't need to worry about URLs.

What you do need to do is to bind your reactivity to something the router changes.

The easiest option is to use parameters from the URL. If you define your route as `/parents/:parentId`, your component can access `params.parentId` which can be used for reactivity (see example in my comment above).

If you can't do that, then you can listen to changes to things like the `$location` store. Since this is a Svelte store, it's fully reactive and you can use that to build reactive statements.

**Comment by ItalyPaleAle** [comment] 2020-05-30 18:24
(Closing this as it's not an issue with the router, but feel free to continue commenting)

**Closed by ItalyPaleAle** 2020-05-30 18:24 UTC
Labels: question

**Comment by crazedVic** [comment] 2020-06-05 21:16
Thanks for pointing me in the right direction.  Took me a while still to get it working but I got there.  For others that end up here, who maybe are as new at svelte as I am, this is what i did to get it working:
```
import { location } from 'svelte-spa-router';
```
then in the script i put this line:
```
$: getBookings($location);
```
this is the fetch function:
```
const getBookings = async (location = null) => {
        status = location.split('/')[2];
        fetch(url + 'shifts/' + status, options)
                .then(res => {
                    if (res.ok) {
                        res.json().then(json => {
                            bookings = json.data;
                        });
                    }
                    else{
                        statusText = "Error loading bookings"
                    }
                })
                .then(res => console.log(res));
    }
```
the format of the url for my app is:
```
/Bookings/{{status}}
```

**Comment by duduindo** [comment] 2020-06-07 19:10
@crazedVic Thank you!
