### ISSUE TITLE
How to react external modifications of window.location?

### ISSUE THREAD

**Issue by zenoli** [ItalyPaleAle/svelte-spa-router#255] opened 2022-02-07 15:52 UTC
I am using [Keycloak](https://www.keycloak.org/) for loging into my app. After successful login, Keycloak should redirect back to `http://localhost:1234/#/myRoute`. However, Keycloak appends some suffixes to this route. The route ends up looking something like this:
`http://localhost:1234/#/myRoute&state=hexstring&session_state=hexstring... etc`
As I defined my route (inside routes.js) as `/myRoute`, the router fails to parse the URL returned by keycloak. Looking at the source code I noticed that keycloak changes the URL back to the "clean" parameterless URL: `http://localhost:1234/#/myRoute` using a call to `window.location.replaceState`. Unfortunately, this call does not get reflexted in the spa-routers internal svelte store (i.e. $location).

I have two workarounds:
1. Use a map and a regex match to find the "ugly" URL with parameters.
2. Manually call the "replace" function to make the the redirect work.

Both options feel hacky and have their drawbacks. Am I using the library wrong? Is there a way to always keep the url in the browser in sync with the internal $location store?

**Comment by ItalyPaleAle** [comment] 2022-02-09 16:02
Closing as this is a question and not a bug in the router, but feel free to add more comments.

**Closed by ItalyPaleAle** 2022-02-09 16:02 UTC
Labels: question
