### ISSUE TITLE
svelte version 3.13.0 breaks use:active

### ISSUE THREAD

**Issue by TorstenDittmann** [ItalyPaleAle/svelte-spa-router#59] opened 2019-11-13 13:18 UTC
Just updated from svelte version 3.12.1 to 3.13.0.

The `node` in `active.js`@`active(node, path, className)`
https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/active.js#L37

is not present anymore.

When I don't give `use:active` a custom css class, everything works fine.

Example using `use:active={'/'}`:

> node: [object HTMLLIElement]
> path: /
> className:undefined

Example using `use:active={'/', 'active'}`:

> node: [object HTMLLIElement]
> path: active
> className:undefined

**Comment by chovy** [comment] 2019-11-14 03:36
I can't get use:link to work. I just get a 404

**Comment by ItalyPaleAle** [comment] 2019-11-14 05:46
Thanks for reporting this. I have confirmed it's a regression in Svelte 2.13+ and opened a bug with the upstream project: https://github.com/sveltejs/svelte/issues/3923

In the meanwhile, please revert back to 2.12.1

**Comment by ItalyPaleAle** [comment] 2019-11-14 15:33
Looks like this will need to be fixed in the router. Since it’s a breaking change, it will happen on a version 2.0, for which there’s another breaking change I’m considering.

I’ll work on this over the weekend

**Closed** 2019-11-17 18:26 UTC

**Comment by ItalyPaleAle** [comment] 2019-11-17 18:27
Merged the fix into master. I'll release this in version 2.0 with a few more things soon, as it's a breaking change
